In [208]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re
import time

In [209]:
HEAD = {
        'User-Agent': "PostmanRuntime/7.20.0",
        'Accept': "*/*",
        'Cache-Control': "no-cache",
        'Postman-Token': "adbba748-cb85-4fb4-8f6a-4be441f19cc3",
        'Host': "m.land.naver.com",
        'Accept-Encoding': "gzip, deflate",
        'Connection': "keep-alive",
        'cache-control': "no-cache"
        }

def parsing_html(id):
    result = requests.get(f"https://m.land.naver.com/article/info/{id}",headers=HEAD,timeout=5)
    soup = BeautifulSoup(result.text,"html.parser")
    if soup.find("div",{"class":"info_list info_list--double"}) is not None:
        if soup.find("div",{"class":"architecture_info"})is not None :
            info = soup.find("div",{"class":"info_list info_list--double"})
            info_name = info.find_all("span",{"class":"tit"})
            info_value = info.find_all("span",{"class":"data"})
            name = []
            value = []
            for i in range(len(info_name)):
                name.append(info_name[i].string)
            for p in range(len(info_value)):
                value.append(info_value[p].string)
            del value[1]
            del name[-1]
            data=pd.DataFrame([value],columns=name)
            info2 = soup.find("div",{"class":"architecture_info"})
            info2_name = info2.find_all("em",{"class":"architecture_item_title"})
            info2_value = info2.find_all("span",{"class":"architecture_item_text"})
            name2 = []
            value2 = []
            for i in range(len(info2_name)):
                name2.append(info2_name[i].string)
            for i in range(len(info2_value)):
                value2.append(info2_value[i].text)
            data2=pd.DataFrame([value2],columns=name2)
            data2["매물번호"]=[id]
            #print(data2)
            datafin = pd.merge(data,data2,on = "매물번호",how = "outer")
            return datafin
            
        else :
            print("건축물대장없음")
            info = soup.find("div",{"class":"info_list info_list--double"})
            info_name = info.find_all("span",{"class":"tit"})
            info_value = info.find_all("span",{"class":"data"})
            name = []
            value = []
            for i in range(len(info_name)):
                name.append(info_name[i].string)
            for p in range(len(info_value)):
                value.append(info_value[p].string)
            del value[1]
            del name[-1]
            data=pd.DataFrame([value],columns=name)
            datafin = data
            return datafin
    else : 
        print("자료없음")
        return None
        #datafin = pd.DataFrame({"매물번호":id,"준공년월":["77"]})
        #datafin.loc[:,"매물번호"]=datafin.loc[:,"매물번호"].astype(np.int64)
        #datafin.loc[:,"준공년월"]=datafin.loc[:,"준공년월"].astype(np.int64)
##MAKE DFTEST(MOTHERDATA)
dftest = pd.read_csv("gangnam.csv")
dftest.rename(columns ={"atclNo":"매물번호" },inplace = True)
dftest.loc[:,"매물번호"]=dftest.loc[:,"매물번호"].astype(np.int64)

In [210]:
def dfframe(x):
    a=[]
    data=parsing_html(x)
    if data is not None:
        a=re.findall("준공년월\w*",str(list(data)))
        a.append("매물번호")
        test=data[a]
        #test=test.iloc[:,[-2,-1]]  ##특정칼럼을 선택하는 방법iloc외에..
        #test.columns =["준공년월","매물번호"]
        test.loc[:,"매물번호"]=test.loc[:,"매물번호"].astype(np.int64)
        return test
    else:
        return None

In [211]:
id1="1928565103"  ## 있는 id
id2="1928352376"
id3 = "1168011300" ##없는 id
id4 = "1928268427"
li = [id1,id3,id4]

In [212]:
print(dfframe(id2))

     준공년월_x   준공년월_y        매물번호
0  1998.03.  1998.03  1928352376

In [213]:
li=dftest["매물번호"]
for i in range(len(li)):
    listdf.append(dfframe(str(li[i])))
    time.sleep(2)
    print("ok")
df_accum = pd.concat(listdf)

건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
ok
건축물대장없음
ok
건축물대장없음
ok
ok
건축물대장없음
ok
자료없음
ok
ok
ok
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
자료없음
ok
ok
건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
ok
건축물대장없음
ok
ok
ok
자료없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
ok
ok
ok
ok
ok
ok
건축물대장없음
ok
ok
건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
자료없음
ok
건축물대장없음
ok
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
건축물대장없음
ok
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
ok
ok
ok
ok
건축물대장없음
ok
ok
ok
ok
건축물대장없음
ok
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
건축물대장없음
ok
ok
ok
ok
ok
건축물대장없음
ok
건축물대장없음
ok
ok
건축물대장없음
ok
ok

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [214]:
print(df_accum)

          매물번호      준공년월    준공년월_x   준공년월_y
0   1928565103  2017.06.       NaN      NaN
0   1928352376       NaN  1998.03.  1998.03
0   1928268427  2005.10.       NaN      NaN
0   1928075688  2005.12.       NaN      NaN
0   1928565103  2017.06.       NaN      NaN
..         ...       ...       ...      ...
0   1927405946  2002.11.       NaN      NaN
0   1927264501  1998.01.       NaN      NaN
0   1927087119       NaN  2013.01.  2013.09
0   1926992055       NaN       NaN      NaN
0   1926913282       NaN  1974.01.  1974.10

[171 rows x 4 columns]

In [215]:
#MERGE
dfnew = pd.merge(dftest,df_accum,on = "매물번호",how ="left")
print(dfnew)

           매물번호    cortarNo rletTpCd tradTpCd flrInfo    prc  spc1  spc2  \
0    1928565103  1168011300      A02       A1    고/10  71000   153    74
1    1928565103  1168011300      A02       A1    고/10  71000   153    74
2    1928565103  1168011300      A02       A1    고/10  71000   153    74
3    1928565103  1168011300      A02       A1    고/10  71000   153    74
4    1928565103  1168011300      A02       A1    고/10  71000   153    74
..          ...         ...      ...      ...     ...    ...   ...   ...
166  1927405946  1168010100      A01       A1     중/7  85000   151   103
167  1927264501  1168010100      A01       A1     고/7  95000   144   126
168  1927087119  1168010400      D02       A1    3/10  68000   216   112
169  1926992055  1168011300      E03       A1       -  38000   345     0
170  1926913282  1168010100      D05       A1    4/-1  95000   275   758

    direction        lat         lng                            atclFetrDesc  \
0          남향  37.474159  127.107065  SS 사진있음 SS 로얄층, 남향, 실입주가능,투자수익형가능.강력추천
1          남향  37.474159  127.107065  SS 사진있음 SS 로얄층, 남향, 실입주가능,투자수익형가능.강력추천
2          남향  37.474159  127.107065  SS 사진있음 SS 로얄층, 남향, 실입주가능,투자수익형가능.강력추천
3          남향  37.474159  127.107065  SS 사진있음 SS 로얄층, 남향, 실입주가능,투자수익형가능.강력추천
4          남향  37.474159  127.107065  SS 사진있음 SS 로얄층, 남향, 실입주가능,투자수익형가능.강력추천
..        ...        ...         ...                                     ...
166        남향  37.501530  127.034505           직접보유매물 역삼역3분 갭투자 올리모델링 구조좋은방4
167       NaN  37.494258  127.038851                            반듯하고  정리잘된집
168       NaN  37.526434  127.049678                              청담동주택가구분상가
169       NaN  37.467434  127.117574                             개발제한구역, 투자용
170        동향  37.499431  127.043905                                     NaN

                                 tagList        rltrNm      준공년월    준공년월_x  \
0              ['4년이내', '화장실두개', '대형평수']    DK공인중개사사무소  2017.06.       NaN
1              ['4년이내', '화장실두개', '대형평수']    DK공인중개사사무소  2017.06.       NaN
2              ['4년이내', '화장실두개', '대형평수']    DK공인중개사사무소  2017.06.       NaN
3              ['4년이내', '화장실두개', '대형평수']    DK공인중개사사무소  2017.06.       NaN
4              ['4년이내', '화장실두개', '대형평수']    DK공인중개사사무소  2017.06.       NaN
..                                   ...           ...       ...       ...
166      ['25년이내', '역세권', '대형평수', '방세개']   한마음공인중개사사무소  2002.11.       NaN
167  ['25년이내', '대형평수', '방네개이상', '화장실두개']    그린공인중개사사무소  1998.01.       NaN
168                    ['10년이내', '주차가능']  사람과집공인중개사사무소       NaN  2013.01.
169                                   []    칠성공인중개사사무소       NaN       NaN
170       ['25년이상', '주차가능', '총4층', '동향']  (주)유일부동산중개법인       NaN  1974.01.

      준공년월_y
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
166      NaN
167      NaN
168  2013.09
169      NaN
170  1974.10

[171 rows x 17 columns]

In [75]:
id1="1928565103"  ## 있는 id
id2="1928352376"
id3 = "1168011300" ##없는 id
id4 = "1928268427"
li = [id1,id3,id4]

In [80]:
df1=mergetable(id1,dftest)
df2=mergetable(id2,df1)
df3=mergetable(id3,df2)
print(df1)
print(df2)

건축물대장없음
자료없음
           매물번호    cortarNo rletTpCd tradTpCd flrInfo    prc  spc1  spc2  \
0    1928565103  1168011300      A02       A1    고/10  71000   153    74
1    1928352376  1168011800      C02       A1     3/4  90000   135    88
2    1928268427  1168010800      A02       A1    7/15  65000   146    79
3    1928075688  1168010500      A02       A1     3/9  75000   137    85
4    1928974832  1168010100      A01       A1     4/7  85000   151   103
..          ...         ...      ...      ...     ...    ...   ...   ...
135  1927405946  1168010100      A01       A1     중/7  85000   151   103
136  1927264501  1168010100      A01       A1     고/7  95000   144   126
137  1927087119  1168010400      D02       A1    3/10  68000   216   112
138  1926992055  1168011300      E03       A1       -  38000   345     0
139  1926913282  1168010100      D05       A1    4/-1  95000   275   758

    direction        lat         lng                            atclFetrDesc  \
0          남향  37.474159  127.107065  SS 사진있음 SS 로얄층, 남향, 실입주가능,투자수익형가능.강력추천
1         NaN  37.490651  127.037719                   전속.실27.전세안고.지하창고,주차가능
2          남향  37.516791  127.040858                       더블역세권 초역세권위치사무실매매
3          남향  37.511450  127.048844                                     NaN
4         NaN  37.501530  127.034505           직접보유 역삼역3분 3억갭투자 올리모델링 대지지분13
..        ...        ...         ...                                     ...
135        남향  37.501530  127.034505           직접보유매물 역삼역3분 갭투자 올리모델링 구조좋은방4
136       NaN  37.494258  127.038851                            반듯하고  정리잘된집
137       NaN  37.526434  127.049678                              청담동주택가구분상가
138       NaN  37.467434  127.117574                             개발제한구역, 투자용
139        동향  37.499431  127.043905                                     NaN

                                 tagList        rltrNm      준공년월
0              ['4년이내', '화장실두개', '대형평수']    DK공인중개사사무소  2017.06.
1      ['25년이상', '대형평수', '방세개', '화장실두개']   헤브론공인중개사사무소       NaN
2               ['15년이내', '역세권', '대형평수']    sk공인중개사사무소       NaN
3        ['15년이내', '역세권', '대형평수', '방세개']    건우공인중개사사무소       NaN
4      ['25년이내', '역세권', '대형평수', '방네개이상']   한마음공인중개사사무소       NaN
..                                   ...           ...       ...
135      ['25년이내', '역세권', '대형평수', '방세개']   한마음공인중개사사무소       NaN
136  ['25년이내', '대형평수', '방네개이상', '화장실두개']    그린공인중개사사무소       NaN
137                    ['10년이내', '주차가능']  사람과집공인중개사사무소       NaN
138                                   []    칠성공인중개사사무소       NaN
139       ['25년이상', '주차가능', '총4층', '동향']  (주)유일부동산중개법인       NaN

[140 rows x 15 columns]
           매물번호    cortarNo rletTpCd tradTpCd flrInfo    prc  spc1  spc2  \
0    1928565103  1168011300      A02       A1    고/10  71000   153    74
1    1928352376  1168011800      C02       A1     3/4  90000   135    88
2    1928268427  1168010800      A02       A1    7/15  65000   146    79
3    1928075688  1168010500      A02       A1     3/9  75000   137    85
4    1928974832  1168010100      A01       A1     4/7  85000   151   103
..          ...         ...      ...      ...     ...    ...   ...   ...
135  1927405946  1168010100      A01       A1     중/7  85000   151   103
136  1927264501  1168010100      A01       A1     고/7  95000   144   126
137  1927087119  1168010400      D02       A1    3/10  68000   216   112
138  1926992055  1168011300      E03       A1       -  38000   345     0
139  1926913282  1168010100      D05       A1    4/-1  95000   275   758

    direction        lat         lng                            atclFetrDesc  \
0          남향  37.474159  127.107065  SS 사진있음 SS 로얄층, 남향, 실입주가능,투자수익형가능.강력추천
1         NaN  37.490651  127.037719                   전속.실27.전세안고.지하창고,주차가능
2          남향  37.516791  127.040858                       더블역세권 초역세권위치사무실매매
3          남향  37.511450  127.048844                                     NaN
4         NaN  37.501530  127.034505           직접보유 역삼역3분 3억갭투자 올리모델링 대지지분13
..        ...        ...         ...                                     ...
135        남향  37.501530  127.034505           직접보유매물 역삼역3분 갭투자 올리모델링 구조좋은방4
136       NaN  37.494258  127.038851                            반듯하고  정리잘된집
137       NaN  37.526434  127.049678                              청담동주택가구분상가
138       NaN  37.467434  127.117574                             개발제한구역, 투자용
139        동향  37.499431  127.043905                                     NaN

                                 tagList        rltrNm    준공년월_x   준공년월_y
0              ['4년이내', '화장실두개', '대형평수']    DK공인중개사사무소  2017.06.      NaN
1      ['25년이상', '대형평수', '방세개', '화장실두개']   헤브론공인중개사사무소       NaN  1998.03
2               ['15년이내', '역세권', '대형평수']    sk공인중개사사무소       NaN      NaN
3        ['15년이내', '역세권', '대형평수', '방세개']    건우공인중개사사무소       NaN      NaN
4      ['25년이내', '역세권', '대형평수', '방네개이상']   한마음공인중개사사무소       NaN      NaN
..                                   ...           ...       ...      ...
135      ['25년이내', '역세권', '대형평수', '방세개']   한마음공인중개사사무소       NaN      NaN
136  ['25년이내', '대형평수', '방네개이상', '화장실두개']    그린공인중개사사무소       NaN      NaN
137                    ['10년이내', '주차가능']  사람과집공인중개사사무소       NaN      NaN
138                                   []    칠성공인중개사사무소       NaN      NaN
139       ['25년이상', '주차가능', '총4층', '동향']  (주)유일부동산중개법인       NaN      NaN

[140 rows x 16 columns]